### ISSUE TITLE
Написать скрипт для создания и удаления бд

### ISSUE THREAD

**Issue by CrazyChris3310** [Vakzu/musical-wars-backend#14]

**Comment by CrazyChris3310** [comment]
На самом деле скрипт для создания таблиц уже есть, и нужно только удаление

**Comment by dmittrey** [comment]
@CrazyChris3310 done see commits:
0e274222eae8d9afb8a01e87a49bd77c3d58405b
292b81c5a6c3aec3b13572d21ae3ebe8ddbc6159
