### ISSUE TITLE
Захэндлить триггер на апдейт таблицы deal

### ISSUE THREAD

**Issue by CrazyChris3310** [Vakzu/musical-wars-backend#24]
Когда происходит покупка эффекта таблица апдейтится и транзакция покупки фиксируется в таблице deal, когда эффект используется, количество в инвентаре уменьшается, и триггер тоже срабатывает. Нужно сделать чтоб при уменьшении количества, транзакция в таблице "deal" не фиксировалась.

**Comment by dmittrey** [comment]
Closed in cebb192672dda4aab9fcbd15f092ced40406e609
